# Generated by Django 5.0 on 2026-09-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="movies.review",
            ),
        ),
    ]
