# Generated by Django 5.0 on 2026-09-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_report_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.review",
            ),
        ),
    ]
